### ISSUE TITLE
Installation fails - status set to notworking in one week

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/zeronet_ynh#3]
Hello,

Your app failed to install on our CI, hence it will be set at notworking status in one week unless installation is fixed.

You can find the complete log here
https://ci-apps.yunohost.org/jenkins/job/zeronet%20(Community)/15/console

It looks like GitHub changed unilaterally the .tar.gz of the zeronet release, hence changing the checksum and making the checksum check fail...

The YunoHost Apps Group

**Comment by whypsi** [comment]
App updated.
